### ISSUE TITLE
Example of how to do a reverse lookup, i.e. get node to return PTR record(s)?

### ISSUE THREAD

**Issue by Nodi-Rubrum** [xk/node-red-contrib-DNSQuery#3]
Example of how to do a reverse lookup, i.e. get node to return PTR record(s)?

**Comment by blaxer** [comment]
+1 to this request, I have tried it and cannot seem to get PTR lookups working....

**Comment by xk** [comment]
node's dns.resolve() can´t do that:

https://github.com/xk/node-red-contrib-DNSQuery/blob/master/dnsquery.js#L100
https://nodejs.org/api/dns.html#dns_dns_resolve_hostname_rrtype_callback

For reverse queries node's got this which we´re not using:

https://nodejs.org/api/dns.html#dns_dns_reverse_ip_callback
