### ISSUE TITLE
Unable to set msg.payload.domain_name

### ISSUE THREAD

**Issue by romprod** [xk/node-red-contrib-DNSQuery#4]
Hi,

I'm trying to set the domain and record type via msg.payload but I can't seem to get any output if I do it via this methods. Can you confirm the correct method please?

I've tried both msg.payload.domain_name and msg.payload.record_type but neither seem to work.

Also your gif show msg.payload.rtype which also does not work for the record type.

`payload: object
domain: "test.com"
type: "TXT"
dns_ip: "8.8.8.8"
topic: ""`

`payload: object
ok: false
domain: ""
type: "A"
answer: undefined
error: "Error: queryA ENODATA"
dns_ip: "127.0.0.11"
topic: ""`

**Comment by xk** [comment]
Hi,

I've updated this (v1.0.7), please try it and tell me if it works fine now:

https://flows.nodered.org/node/node-red-contrib-dnsquery
https://www.npmjs.com/package/node-red-contrib-dnsquery

I'm testing it with this flow:
https://gist.github.com/xk/69842345b6212d7729f7ee7106884609

Cheers.

**Comment by romprod** [comment]
Thankyou, yes that fixed the problem.

**Comment by xk** [comment]
you're welcome @romprod
